services:
  springboot-app:
    build: .
    container_name: springboot-app
    expose:
      - "8081"  # internal port your app listens on
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx-inventory-proxy
    ports:
      - "8081:80"   # external port 8081 mapped to internal 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - springboot-app
    networks:
      - backend

networks:
  backend:
    driver: bridge

